### ISSUE TITLE
Audios of the Hindi letters are not playing.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#372] opened 2023-04-21 06:00 UTC
**Describe the bug**
In some of the levels the audios of the Hindi letters are not playing.
Levels with the issue:

- Lv. 67, pz 4
- Lv. 70, pz 4
- Lv. 71, pz 5

**To Reproduce**
1. Install the latest CR Container app which has FTM Hindi and open it.
2. Play the above mentioned levels.

**Expected Behavior**
The audio of the letters should play when the puzzle starts and should play when user clicks on the prompt. 

**Smartphone (please complete the following information):**
 - Device: MI Note 6 pro
 - OS: Android 9

**Additional context**

**Comment by burrage** [comment] 2023-04-25 21:58
@Ashish1998 Could I have you do a little more investigation work into this particular issue please? 

Is the requested audio file not uploaded to the server? If so, what is the anticipated file name?

Thanks!

**Comment by Ashish1998** [comment] 2023-04-26 08:33
Hiii @burrage these are the links of the audios which are not playing.
https://curiousreader.org/wp-content/uploads/HINDI_sounds_letters_%E0%A4%A2%E0%A4%83.wav
https://curiousreader.org/wp-content/uploads/HINDI_sounds_letters_%E0%A4%A1%E0%A5%87.wav
https://curiousreader.org/wp-content/uploads/HINDI_sounds_letters_%E0%A4%AF%E0%A5%8C.wav
https://curiousreader.org/wp-content/uploads/HINDI_sounds_letters_%E0%A4%B0%E0%A5%8C.wav

**Comment by burrage** [comment] 2023-04-27 17:49
@Ashish1998 Well that makes it tough to figure out what file it is based on the filename, huh? :-)

Can I show you how we might find the root cause of this issue from a QA standpoint for the first audio issue and then we can have you try the other two yourself as practice? You can ask me for help in figuring out the other two if you get stuck, but I want to make sure you have some time to practice on your own first before I or someone else on the team steps in to help.

This will be a good QA skill to develop because not only will you find that a bug exists, but you'll be helping to discover what could be causing it! This will save the developers a lot of time and give them a better idea of where to fix the problem. 

OK first things first... Would you happen to know how to read a JSON file by chance? And do you know how to "pretty" a JSON file to be more human-readable? If not, that's the best place to start so let me know and we can run through that if you've never gone through that process.

To explain the tactic I'm using to find the root cause of the issue... I'm going into the AllHINDI.json file in an editor, "pretty"ing the file so it is no longer minified and on one line, and searching by the "LevelNumber" field.

In this case, I'm looking for "LevelNumber": "66" (the JSON levels start from 0 instead of 1 so they will be "one off" in comparison to what we see in the Feed The Monster game) and then finding "SegmentNumber": "3" (aka: puzzle 4-- again the segments start at 0 instead of 1 so again they will be "one off"). 

From here, I see that the actual file name will be called something like:

![Screenshot 2023-04-27 at 12 12 43 PM](https://user-images.githubusercontent.com/5167186/234940957-75d80e74-824a-4437-bb96-78c519880734.png)

A little better than something like %E0%A4%A2%E0... right?!? Let me copy that character that I'd be looking for. 

OK so now I'm going into the Hindi letter sounds directory:

https://github.com/curiouslearning/ftm-languagepacks/tree/master/HINDI/sounds/letters

And searching for that character and a-ha! I'm seeing something off already:

![Screenshot 2023-04-27 at 12 15 12 PM](https://user-images.githubusercontent.com/5167186/234941909-928e654d-8677-4168-abea-9ebcd0a93780.png)

Notice how the filenae is ढः.wav .wav? That doesn't look right... 

So... From here, what I would do is get in contact with the original developer that downloaded all these files from Github and added the appropriate HINDI_sounds_letters_ prefix to the filename. We'll ask them to see if they have a file on their machine called:

HINDI_sounds_letters_ढः.wav .wav

In which case, we'd have to change the filename to remove the repeated file extension:

HINDI_sounds_letters_ढः.wav

I would then have that developer upload that newly renamed file to Wordpress and try that level and puzzle again and hopefully, that resolves the issue!

Anyway... That's the approach I would take. Want to have a pass at these next two and let me know what you find?

Thanks @Ashish1998 !

**Comment by Ashish1998** [comment] 2023-05-02 08:29
Hiii @burrage thanks for the approach you told, i have found the file name of the other 2 letter audios, please check if it is proper, the file name.

- ढः.wav .wav
- यौ.wavयौ_pair.wav
- रौ.wav .wav
- डे.wav .wav

**Comment by burrage** [comment] 2023-05-02 19:20
No problem, @Ashish1998 !

Bingo! Looking at the rest of these filenames, they look off at the source and wouldn't match what the JSON URL would be pointing to.

There're two separate approaches we could take here to solve the issue:

1.) We could update the URL path in the JSON to be more in line with what we found here (e.x. 'https://curiousreader.org/wp-content/uploads/HINDI_sounds_letters_रौ.wav .wav').

OR

2.) We could rename these files locally (e.x. HINDI_sounds_letters_रौ.wav (removing the additional ' .wav') and re-upload them to the server. We could also make a commit to the original assets repo with a renamed filename (e.x. रौ.wav) so that the source would be standardized.

Which do you think would be a better approach @Ashish1998 ? And would you want to want to give it a try and see if it resolves the issues?

**Comment by Ashish1998** [comment] 2023-05-03 07:26
Hiii @burrage I discussed with the developers, so updating the URL path might be a better choice they said.

**Comment by burrage** [comment] 2023-05-04 15:49
I would say #2 would be the better approach but I also have some inside information (;-)) of how the JSON is created so let me share that as I think it'll be important information as we get you troubleshooting and fixing more issues in the JSON files.

Basically, we have a Google Sheet where each level is laid out-- what type of level is it, what's the target, etc. Here's an example Google Sheet:

https://docs.google.com/spreadsheets/d/1PyWYpfwg04fhrcnkSNFM7cSQTNj34XV3NS_iAMe8IfY/edit?usp=sharing

This allows a non-technical content specialist to say what letter(s)/word(s) they want to target on each level in a format that is friendly to a non-technical individual.

This sheet is what gets converted into the JSON file. Each puzzle target is parsed, left to right and separated by commas, and the "foil" stones are randomly selected based on what other letters are "available" for this level. So for instance, in level 1, this is why the target and foils would always be either a, c, or t.

Where approach #2 is the better approach is... what happens when someone changes this Google Sheet? The JSON would be regenerated, but we would have the wrong URL again and we'd have to fix it every time we regenerate the JSON file. With approach #2, we are fixing the root cause of the issue-- the original audio filename is not standardized.

Does that make sense?

Any questions?

**Comment by Ashish1998** [comment] 2023-05-05 05:38
Yeah @burrage i understood it, we can follow this approach.

**Comment by burrage** [comment] 2023-05-23 15:07
@divyahariharan2103 Un-assigning myself and Ashish M from this task and re-assigning to @amitsinghsutara as this SHOULD overlap with #386 already assigned to Amit.

**Comment by Ashish1998** [comment] 2023-05-26 06:36
https://curiousreader.org/wp-content/uploads/HINDI_sounds_letters_डे.wav
https://curiousreader.org/wp-content/uploads/HINDI_sounds_letters_ढः.wav
https://curiousreader.org/wp-content/uploads/HINDI_sounds_letters_यौ.wav
https://curiousreader.org/wp-content/uploads/HINDI_sounds_letters_रौ.wav

**Closed** 2023-06-02 06:18 UTC
Labels: bug, High Priority, Content
